# -*- coding: utf-8 -*-
"""Despliegue-Videojuegos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wrhZK4QfSn5fvtVx0qH5cHiPK5HnSMWc

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros: normalizar, dummies
- Aplicamos el modelo para la predicción
"""

#Cargamos librerías principales

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Cargamos el modelo
import pickle
filename = 'modelo-reg.pkl'
modelo, min_max_scaler, variables = pickle.load(open(filename, 'rb'))
modelo

#Cargamos los datos futuros
#esto es para que empiecen los datos desde el archivo, pero para la pagina lo pongo como comentario
#data = pd.read_csv("/videojuegos-datosFuturos.csv")
#data.head()

#Interfaz grafica

#Se crea interfaz gráfica con streamlit para captura de los datos
#streamlit es una libreria para html, en google colab no ejecuta
#todas las variables se deben llamar igual

import streamlit as st

st.title('Predicción de inversión en una tienda de videojuegos')

Edad = st.slider('Edad', min_value=14, max_value=52, value=20, step=1)
videojuego = st.selectbox('Videojuego', ["'Mass Effect'","'Battlefield'", "'Fifa'","'KOA: Reckoning'","'Crysis'","'Sim City'","'Dead Space'","'F1'"])
#las comillas sencillas vienen del nombre
Plataforma = st.selectbox('Plataforma', ["'Play Station'", "'Xbox'","PC","Otros"])
Sexo = st.selectbox('Sexo', ['Hombre', 'Mujer'])
Consumidor_habitual = st.selectbox('Consumidor_habitual', ['True', 'False'])


#Dataframe
datos = [[Edad, videojuego,Plataforma,Sexo,Consumidor_habitual]]
data = pd.DataFrame(datos, columns=['Edad', 'videojuego','Plataforma','Sexo','Consumidor_habitual']) #Dataframe con los mismos nombres de variables

#preparación datos
#creacion dummies

#Se realiza la preparación de datos
data_preparada=data.copy()

#En despliegue drop_first= False
data_preparada = pd.get_dummies(data_preparada, columns=['videojuego', 'Plataforma','Sexo', 'Consumidor_habitual'], drop_first=False, dtype=int)
data_preparada.head()

# esto lo hago para que si falta variables, las pone y si sobran las quita
#esto es con el fin que al modelo le entren las mismas variables con las que se entreno
#Se adicionan las columnas faltantes
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

# como mi modelo es arbol no se normaliza, se si utilizamos otro toca hacerlo
#Se normaliza la edad para predecir con Knn, Red, SVM, Reg
#En los despliegues no se llama fit
#data_preparada[['Edad']]= min_max_scaler.transform(data_preparada[['Edad']])
#data_preparada.head()

"""PREDICCIONES"""

#Hacemos la predicción con el Tree
Y_pred = modelo.predict(data_preparada)
print(Y_pred)

# esto es para que al final se vea la prediccion
data['Prediccion']=Y_pred
data.head()

data

# Recordar medida de error del modelo
 #mi mape es 10.44
st.warning("El modelo tiene un error del 10.44% (mape: error porcentual)")

